### ISSUE TITLE
failed `build:ldo`: doesn't show from which file the error comes from.

### ISSUE THREAD

**Issue by thhck** [o-development/ldo#19]
Running `npm run build:ldo` I got an error message:
```
parser.js:16
            var error = new Error(str);
                        ^

Error: Parse error on line 7:
...:title xsd:string  ex:description xsd:s
```

I do have the line number where the error comes from but not the file, it would be convinient to have it in there too.

**Comment by jaxoncreed** [comment]
Fixed in https://github.com/o-development/ldo/pull/38
