### ISSUE TITLE
Couldn't find module @inrupt/solid-client-authn-browser

### ISSUE THREAD

**Issue by Mendistern** [o-development/ldo#8]
When following the tutorial on [your github page](https://github.com/o-development/ldo/blob/main/documentation/solid-react-tutorial.md)

I get the module not found error.

Installing it separately resolved the issue.

**Comment by jaxoncreed** [comment]
Hello, thanks for the comment. The tutorial was old and has since been deleted. The best tutorial to use is at [ldo.js.org](https://ldo.js.org)
